# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=128)),
                ('Salt', models.CharField(max_length=16)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
            ],
        ),
    ]
