# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenMew', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Salt',
            new_name='salt',
        ),
    ]
