# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'App_Prototype_Alpha_001' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App_Prototype_Alpha_001
pod 'Firebase'
pod 'FirebaseAuth'
  target 'App_Prototype_Alpha_001Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App_Prototype_Alpha_001UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
