-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 19:19:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` CHAR(128) NOT NULL,
  `Salt` CHAR(16) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `AddressLine1` VARCHAR(45) NULL,
  `AddressLine2` VARCHAR(45) NULL,
  `AddressCity` VARCHAR(45) NULL,
  `AddressState` VARCHAR(2) NULL,
  `AddressZip` INT(5) NULL,
  PRIMARY KEY (`AddressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `RestaurantID` INT NOT NULL AUTO_INCREMENT,
  `RestaurantName` VARCHAR(45) NULL,
  `RestaurantDesc` TEXT(255) NULL,
  `AddressID` INT NULL,
  PRIMARY KEY (`RestaurantID`),
  INDEX `AddressID_idx` (`AddressID` ASC),
  CONSTRAINT `AddressID`
    FOREIGN KEY (`AddressID`)
    REFERENCES `mydb`.`Address` (`AddressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table` (
  `TableID` INT NOT NULL AUTO_INCREMENT,
  `TableName` VARCHAR(45) NULL,
  `TableCode` VARCHAR(255) NULL,
  `RestaurantID` INT NULL,
  PRIMARY KEY (`TableID`),
  INDEX `RestaurantID_idx` (`RestaurantID` ASC),
  CONSTRAINT `RestaurantID`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `mydb`.`Restaurant` (`RestaurantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Server` (
  `ServerID` INT NOT NULL AUTO_INCREMENT,
  `ServerFirstName` VARCHAR(45) NULL,
  `ServerLastName` VARCHAR(45) NULL,
  `ServerEmployeeID` VARCHAR(45) NULL,
  `RestaurantID` INT NULL,
  PRIMARY KEY (`ServerID`),
  INDEX `RestaurantID_idx` (`RestaurantID` ASC),
  CONSTRAINT `RestaurantID`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `mydb`.`Restaurant` (`RestaurantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `TicketID` INT NOT NULL AUTO_INCREMENT,
  `RestaurantID` INT NULL,
  `TableID` INT NULL,
  `ServerID` INT NULL,
  `Tip` DECIMAL(10,2) NULL,
  `DateCreated` DATETIME NULL,
  `DateLastModified` DATETIME NULL,
  PRIMARY KEY (`TicketID`),
  INDEX `RestaurantID_idx` (`RestaurantID` ASC),
  INDEX `TableID_idx` (`TableID` ASC),
  INDEX `ServerID_idx` (`ServerID` ASC),
  CONSTRAINT `RestaurantID`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `mydb`.`Restaurant` (`RestaurantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TableID`
    FOREIGN KEY (`TableID`)
    REFERENCES `mydb`.`Table` (`TableID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ServerID`
    FOREIGN KEY (`ServerID`)
    REFERENCES `mydb`.`Server` (`ServerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemCategory` (
  `ItemCategoryID` INT NOT NULL AUTO_INCREMENT,
  `ItemCategoryName` VARCHAR(45) NULL,
  PRIMARY KEY (`ItemCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(45) NULL,
  `ItemDesc` TEXT(255) NULL,
  `RestaurantID` INT NULL,
  `ItemCategoryID` INT NULL,
  `ItemPhoto` VARCHAR(255) NULL,
  `ItemPrice` DECIMAL(10,2) NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `ItemCategoryID_idx` (`ItemCategoryID` ASC),
  INDEX `RestaurantID_idx` (`RestaurantID` ASC),
  CONSTRAINT `ItemCategoryID`
    FOREIGN KEY (`ItemCategoryID`)
    REFERENCES `mydb`.`ItemCategory` (`ItemCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RestaurantID`
    FOREIGN KEY (`RestaurantID`)
    REFERENCES `mydb`.`Restaurant` (`RestaurantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemOrdered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemOrdered` (
  `ItemOrderedID` INT NOT NULL AUTO_INCREMENT,
  `TicketID` INT NULL,
  `UserID` INT NULL,
  `ItemID` INT NULL,
  PRIMARY KEY (`ItemOrderedID`),
  INDEX `TicketID_idx` (`TicketID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  INDEX `ItemID_idx` (`ItemID` ASC),
  CONSTRAINT `TicketID`
    FOREIGN KEY (`TicketID`)
    REFERENCES `mydb`.`Ticket` (`TicketID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IngredientCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IngredientCategory` (
  `IngredientCategoryID` INT NOT NULL AUTO_INCREMENT,
  `IngredientCategoryName` VARCHAR(45) NULL,
  PRIMARY KEY (`IngredientCategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `IngredientID` INT NOT NULL AUTO_INCREMENT,
  `IngredientName` VARCHAR(45) NULL,
  `IngredientCategoryID` INT NULL,
  PRIMARY KEY (`IngredientID`),
  INDEX `IngredientCategoryID_idx` (`IngredientCategoryID` ASC),
  CONSTRAINT `IngredientCategoryID`
    FOREIGN KEY (`IngredientCategoryID`)
    REFERENCES `mydb`.`IngredientCategory` (`IngredientCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemCustomization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemCustomization` (
  `ItemCustomizationID` INT NOT NULL AUTO_INCREMENT,
  `ItemOrderedID` INT NULL,
  `IngredientID` INT NULL,
  `AddOrRemove` TINYINT(1) NULL,
  PRIMARY KEY (`ItemCustomizationID`),
  INDEX `ItemOrderedID_idx` (`ItemOrderedID` ASC),
  INDEX `IngredientID_idx` (`IngredientID` ASC),
  CONSTRAINT `ItemOrderedID`
    FOREIGN KEY (`ItemOrderedID`)
    REFERENCES `mydb`.`ItemOrdered` (`ItemOrderedID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IngredientID`
    FOREIGN KEY (`IngredientID`)
    REFERENCES `mydb`.`Ingredient` (`IngredientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemIngredient` (
  `ItemIngredientID` INT NOT NULL AUTO_INCREMENT,
  `ItemID` INT NULL,
  `IngredientID` INT NULL,
  PRIMARY KEY (`ItemIngredientID`),
  INDEX `ItemID_idx` (`ItemID` ASC),
  INDEX `IngredientID_idx` (`IngredientID` ASC),
  CONSTRAINT `ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `mydb`.`Item` (`ItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IngredientID`
    FOREIGN KEY (`IngredientID`)
    REFERENCES `mydb`.`Ingredient` (`IngredientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
