# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Menu_Server_App_Prototype_001' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Menu_Server_App_Prototype_001
pod 'Firebase'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
pod 'Firebase/Core’
pod 'Firebase/Messaging’
pod 'Firebase/Storage’
end
